module.exports = {
  // Only search for tests in the dist directory emitted by TypeScript
  roots: ['<rootDir>/tests'],

  // Include all .spec.js files generated by the TypeScript build
  testRegex: '.*.test.js$',

  testEnvironment: 'testit-adapter-jest',

  globalSetup: 'testit-adapter-jest/dist/globalSetup.js',
  globalTeardown: 'testit-adapter-jest/dist/globalTeardown.js',
  reporters: [
    "default",
    ["jest-junit", {
      outputFile: "results/test-results.xml",
      ancestorSeparator: " > ",
    }]
  ],

  testEnvironmentOptions: {
    url: "https://team-okp8.testit.software",
    projectId: "9cc7c239-63d7-47b7-af0c-a307488b08b3",
    privateToken: "ejhzdHM0NVpKREZvVzNVclRK",
    configurationId: "2a7e3e25-9afa-4d52-8eea-54d80e4f7444",
    testRunName: "Run",
    adapterMode: 2,
    certValidation: false,
    automaticCreationTestCases: true,
  },
};
