module.exports = {
  // Only search for tests in the dist directory emitted by TypeScript
  roots: ['<rootDir>/tests'],

  // Include all .spec.js files generated by the TypeScript build
  testRegex: '.*.test.js$',

  testEnvironment: 'testit-adapter-jest',
  globalSetup: 'testit-adapter-jest/dist/globalSetup.js',
  globalTeardown: 'testit-adapter-jest/dist/globalTeardown.js',
  reporters: [
    "default",
    ["jest-junit", {
      outputFile: "results/test-results.xml",
      ancestorSeparator: " > ",
    }]
  ]
};
